# Generated by Django 5.2.13 on 2026-05-04 19:18

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_enable_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
