# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="ai_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="note",
            name="embedding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="embedding_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="note",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="note",
            name="embedding_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="embedding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="processing_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="note",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("fallback", "Fallback"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="note",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=settings.EMBEDDING_DIMENSIONS,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(max_length=50)),
                ("provider_model", models.CharField(blank=True, max_length=255)),
                ("latency_ms", models.PositiveIntegerField()),
                ("success", models.BooleanField()),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_call_logs",
                        to="notes.chatmessage",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_call_logs",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task_type", "created_at"],
                        name="notes_aical_task_ty_ab5b50_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="notes_aical_success_762f70_idx",
                    ),
                ],
            },
        ),
    ]
